codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project: yes
    patch: yes
    changes: yes
    # Disable failures while the coverage is poor
    informational: true

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
